### ISSUE TITLE
Add Coverity scan to travis-ci

### ISSUE THREAD

**Issue by Alan-R** [assimilation/assimilation-official#11]
Not sure how to do this, but Coverity implies it can be done. https://scan.coverity.com/users/sign_in. Can also import the repository somehow. I have a script which does it as well, but on-demand (manually).

**Comment by Alan-R** [comment]
Here's a better description: https://scan.coverity.com/travis_ci

**Comment by borgified** [comment]
need more info. it looks like you ran this before. what commands did you use? i got as far as getting github, travisci and coverity hooked up but coverity complains:

[WARNING] No files were emitted. This may be due to a problem with your configuration
or because no files were actually compiled by your build command.

**Comment by Alan-R** [comment]
I'll email you my coverity file.  Not sure how this works in the travis 
world...

**Comment by Alan-R** [comment]
Sorry I forgot to include this before. Let me attach my coverity script here.... You need to create a .coverity file with some credentials in it. I think that should be passably obvious from the script. You should be able to get the credentials from your project-level access to coverity.

Obviously don't want to put the credentials in github...
[coverity.txt](https://github.com/assimilation/assimilation-official/files/12813/coverity.txt)
